#!/usr/bin/sh

# autostart
sxhkd &

# bsp rules

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# startup
exec /usr/local/bin/polybar topbar &
exec wpg -s lookieWP.png &
exec synclient VertScrollDelta=-75 RightButtonAreaLeft=0 RightButtonAreaTop=0 &
exec --no-startup-id nm-applet &
exec compton --backend glx &
