#!/usr/bin/sh

# autostart

dbus-launch sxhkd &
dunst &

# bsp prefs

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap           10

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config paddingless_monocle  true

# colors

get_xrdb_color () {
	return "echo \"$(cat ~/.Xresources | grep -e '\*color$1:' | awk -F' ' '{print $NF}')\""
}

bspc config normal_border_color "#10151b" 
bspc config focused_border_color "#98d1ce"
# $(echo \"$(cat ~/.Xresources | grep -e '\*color4:' | awk -F' ' '{print $NF}')\")
# window rules

bspc rule -a feh state=floating

# startup

exec nitrogen --restore &
exec --no-startup-id nm-applet &
exec compton --backend glx -f -D 2 &
bash /home/turtlebasket/.config/bspwm/bspwm_colors.sh &
